# Generated by Django 4.2.6 on 2023-10-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_profile_location_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='username',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='blog.profile'),
            preserve_default=False,
        ),
    ]
