# Generated by Django 4.2.6 on 2023-10-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_username_blogpost_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='blog.profile'),
        ),
    ]
